config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'
  get 'about' => 'welcome#about'

  resources :sleeplogs

  resources :todos

  resources :reminders do
    resources :user_reminders
  end

  resources :diaries
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  before_validation

  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :title, presence: true
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :js

  def index
    @user = current_user
    @todos = Todo.where(user: @user).order(created_at: :desc)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    if @todo.save
    else
      flash.now[:errors] = @todo.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
  end

  def update
    @todo = Todo.find(params[:id])
    respond_to do |format|
      if @todo.update_attributes(todo_params)
        format.html { redirect_to(@todo, notice: 'User was successfully updated.') }
        format.json { respond_with_bip(@todo) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(@todo) }
      end
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :due, :completed, :starred)
  end
end

app/views/todos/_form.html.haml
#todo
  = simple_form_for @todo, remote: true do |f|
    .row
      .columns.small-12.medium-8= f.input :title
    .row
      .columns.small-12.medium-8= f.date_field :due
    .row
      .columns.small-12.medium-4= f.input :completed, as: :boolean, checked_value: true, unchecked_value: false
      .columns.small-12.medium-4.end= f.input :starred, as: :boolean, checked_value: true, unchecked_value: false
    .button.create_todo_button= f.submit

app/views/todos/_todo.html.haml
= div_for todo do
  %h3.to_do_item= best_in_place todo, :title
  - if todo.due
    = l todo.due
  %p.delete_todo= link_to "Delete To-Do", todo, remote: true, method: :delete

app/views/todos/create.js.erb
$('#todo-form').slideUp(350);
$('#todos-content').prepend("<%= j (render @todo) %>");

app/views/todos/destroy.js.erb
$('.delete_todo').bind('ajax:success', function() {
  $(this).closest('div').slideUp(100);
});

app/views/todos/edit.js.erb
$('#todo-form').html("<%= j (render 'form') %>");
$('#todo-form').slideDown(350);

app/views/todos/index.html.haml
.row.top_of_todos
  %h3.small-11.small-offset-1.columns#todos= link_to "Add To-Do", new_todo_path, remote: true
  .small-11.small-offset-1.columns#todo-form
  .small-11.small-offset-1.columns#todos-content= render @todos

app/views/todos/new.js.erb
$('#todo-form').html("<%= j (render 'form') %>");
$('#todo-form').slideDown(350);