config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'
  get 'about' => 'welcome#about'

  resources :sleeplogs

  resources :todos

  resources :reminders do
    resources :user_reminders
  end

  resources :diaries
end

app/models/sleeplog.rb
class Sleeplog < ActiveRecord::Base
  belongs_to :user
  validate :date_cannot_be_in_future

  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :date, presence: true
  validates :date, uniqueness: { scope: :user_id }
  validates :hours, presence: true, numericality: { greater_than: 0, less_than: 16 }

  private

  def date_cannot_be_in_future
    if date.present? && date > Date.today
      errors.add(:date, "can't be in the future")
    end
  end
end

app/controllers/sleeplogs_controller.rb
class SleeplogsController < ApplicationController
  before_action :authenticate_user!
  respond_to :js
  respond_to :html

  def index
    @user = current_user
    @sleeplogs = Sleeplog.where(user: @user).order(date: :asc)

    respond_to do |format|
      format.html
      format.json do
        dates = @sleeplogs.map { |sleeplog| sleeplog.date }
        hours = @sleeplogs.map { |sleeplog| sleeplog.hours }
        render json: [dates, hours]
      end
    end
  end

  def show
  end

  def new
    @sleeplog = Sleeplog.new
  end

  def create
    @sleeplog = Sleeplog.new(sleeplog_params)
    @sleeplog.user = current_user
    respond_to do |format|
      if @sleeplog.save
        format.html do
          flash[:notice] = "Sleeplog added successfully"
        end
        format.js do
          @sleeplogs = Sleeplog.where(user: current_user).order(date: :asc)
          @dates = @sleeplogs.pluck(:date).to_json
          @hours = @sleeplogs.pluck(:hours).to_json
        end
      else
        format.html do
          flash[:alert] = @sleeplog.errors.full_messages.join(". ")
          render :new
        end
        format.js do
          @sleeplogs = Sleeplog.where(user: current_user).order(date: :asc)
          @dates = @sleeplogs.pluck(:date).to_json
          @hours = @sleeplogs.pluck(:hours).to_json
          flash.now[:alert] = @sleeplog.errors.full_messages.join(". ")
        end
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def sleeplog_params
    params.require(:sleeplog).permit(:date, :hours, :quality, :notes, :in_bed_time, :fall_asleep_time, :wake_up_time, :sleeping_pill)
  end
end

app/views/sleeplogs/_form.html.haml
.row
  #sleeplog
    = simple_form_for Sleeplog.new, remote: true do |f|
      %ul.small-block-grid-2
        %li= f.label :date, "DATE"
        %li= f.label :in_bed_time, "IN BED TIME"
        %li.date= f.date_field :date, label: "DATE", value: Date.today - 1, label: false
        %li.time= f.time_field :in_bed_time, include_blank: true, label: false

        %li= f.label :hours, "HOURS SLEPT"
        %li= f.label :fall_asleep_time, "FALL ASLEEP TIME"
        %li.hours= f.input :hours, collection: 0..16, label: false
        %li= f.time_field :fall_asleep_time, include_blank: true, label: false

        %li= f.label :quality, "QUALITY"
        %li= f.label :wake_up_time, "WAKE UP TIME"
        %li.quality= f.input :quality, collection: %w{Great Good Average OK Bad}, label: false
        %li.time= f.time_field :wake_up_time, include_blank: true, label: false

        %li= f.input :sleeping_pill, as: :boolean, checked_value: true, label: "SLEEPING PILL?", unchecked_value: false

      .notes= f.input :notes, as: :text, label: false, placeholder: "NOTES"
      #sleeplog_button_div
        .button#sleeplog_button= f.submit

app/views/sleeplogs/_sleeplog.html.haml
.single_sleeplog{ id: "sleeplog_id_#{sleeplog.id}" }
  .sleeplog_table
    .row.headers
      .small-6.columns.hours= "#{sleeplog.hours} HOURS"
      .small-6.columns.date= "#{l sleeplog.date}"
    .row.titles
      .small-3.columns WENT TO BED
      .small-3.columns FELL ASLEEP
      .small-3.columns WOKE UP
      .small-3.columns SLEEPING PILL
    .row.info
      - if sleeplog.in_bed_time
        .small-3.columns= l sleeplog.in_bed_time
      - else
        .small-3.columns --:--
      - if sleeplog.fall_asleep_time
        .small-3.columns= l sleeplog.fall_asleep_time
      - else
        .small-3.columns --:--
      - if sleeplog.wake_up_time
        .small-3.columns= l sleeplog.wake_up_time
      - else
        .small-3.columns --:--
      - if sleeplog.sleeping_pill == true
        .small-3.columns YES
      - else
        .small-3.columns NO

    .extra_info
      - unless sleeplog.quality.blank?
        = "Quality: #{sleeplog.quality}"
      - unless sleeplog.notes.blank?
        = "Notes: #{sleeplog.notes}"

      - if Diary.where(user: current_user, date: sleeplog.date).present?
        - Diary.where(user: current_user, date: sleeplog.date).each_with_index do |diary, index|
          %p= link_to "Diary entry mood: #{(diary.sentiment * 100).round}%", diary_path(diary)

app/views/sleeplogs/create.js.erb
$('#myModal').foundation('reveal', 'close');
$('#sleeplogs-content').prepend("<%= j (render @sleeplog) %>");
barHighChart(<%= raw(@dates) %>, <%= @hours %>);
$(".flashes").html("<%= j flash[:alert] %>");

app/views/sleeplogs/index.html.haml
.row.top_of_sleeplogs
  .text-center.sleeplogs_menu.small-2.small-offset-1.columns#graph_link= link_to "GRAPH", "#"
  .text-center.sleeplogs_menu.small-2.small-offset-1.columns#log_link= link_to "LOG", "#"
  .small-1.columns
%br
.row
  %a.small-offset-1.columns{"data-reveal-id" => "myModal", :href => "#"} ADD A NEW SLEEPLOG


#myModal.reveal-modal{"aria-hidden" => "true", "aria-labelledby" => "modalTitle", "data-reveal" => "", :role => "dialog"}
  = render 'new'
  %a.close-reveal-modal{"aria-label" => "Close"} &#215;


.row
  .small-11.small-offset-1.columns#container-1
.row
  .small-11.small-offset-1.columns#sleeplog-form

.row
  .small-11.small-offset-1.columns#sleeplogs-content
    = render @sleeplogs.reverse

app/views/sleeplogs/sleeplog.js.erb
$(document).ready(function() {
  $('.single_sleeplog' ).on("click", function(event) {
    $(".extra_info").show();
  });
});