config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'
  get 'about' => 'welcome#about'

  resources :sleeplogs

  resources :todos

  resources :reminders do
    resources :user_reminders
  end

  resources :diaries
end

app/views/layouts/_login.html.haml
= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
  .row
    = f.input :email, required: false, autofocus: true, placeholder: "Email", label: false
  .row
    = f.input :password, required: false, placeholder: "Password", label: false
  .row
    = link_to "FORGOT YOUR PASSWORD?", new_user_password_path
  .row
    .inherit.button= f.submit "SIGN IN"
  .row
    = f.input :remember_me, label: "REMEMBER ME", as: :boolean if devise_mapping.rememberable?
  .row
    #bottom_right_sign_up= link_to "SIGN UP"

app/views/layouts/_navbar.html.haml
.top-bar{ "data-topbar" => "", :role => "navigation" }
  %ul.title-area
    %li.name

      %h1#shostakodech
        %a.home{:href => root_path} Sleeptracker

    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Right Nav Section
    %ul.right
      %li.active
        - if user_signed_in?
          %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
          %li= link_to 'Edit Account Details', edit_user_registration_path
        - else
          %li.has-dropdown
            %a{:href => "#"} Account
            %ul.dropdown
              %li.account_links= link_to 'Sign In', new_user_session_path
              %li.account_links= link_to 'Sign Up', new_user_registration_path
    %ul.left

app/views/layouts/_sidebar.html.haml
.sidebar.columns.small-12.medium-3.large-2
  .text-center.home_path
    = link_to root_path do
      INSOMNIAPP
  - if controller_name == "sleeplogs"
    = link_to sleeplogs_path do
      #sidebar_sleeplog.highlighted SLEEPLOGS
  - else
    = link_to sleeplogs_path do
      #sidebar_sleeplog.sidebar_links SLEEPLOGS
  - if controller_name == "todos"
    = link_to todos_path do
      #sidebar_todo.highlighted TO-DOS
  - else
    = link_to todos_path do
      #sidebar_todo.sidebar_links TO-DOS
  - if controller_name == "reminders"
    = link_to reminders_path do
      #sidebar_reminder.highlighted REMINDERS
  - else
    = link_to reminders_path do
      #sidebar_reminder.sidebar_links REMINDERS
  - if controller_name == "diaries"
    = link_to diaries_path do
      #sidebar_diary.highlighted DIARIES
  - else
    = link_to diaries_path do
      #sidebar_diary.sidebar_links DIARIES
  .bottom_bar
    .bottom_link= link_to "SIGN OUT", destroy_user_session_path, method: :delete
    .bottom_link= link_to "EDIT ACCOUNT", edit_user_registration_path

app/views/layouts/_signup.html.haml
= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
  = f.error_notification
  .row
    = f.input :first_name, required: true, autofocus: true, label: false, placeholder: "First Name"
  .row
    = f.input :last_name, required: true, autofocus: true, label: false, placeholder: "Last Name"
  .row
    = f.input :phone, required: true, autofocus: true, label: false, placeholder: "Phone Number"
  .row
    = f.input :email, required: true, autofocus: true, label: false, placeholder: "Email"
  .row
    = f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), label: false, placeholder: "Password"
  .row
    = f.input :password_confirmation, required: true, label: false, placeholder: "Password Confirmation"
  .row
    .inherit.button= f.submit "SIGN UP"
  .row
    #bottom_right_sign_in= link_to "SIGN IN"

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Sleeptracker"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body

  - if controller_name == "welcome"
    .welcome.small-12.medium-6.columns
      #welcome-text
        #welcome-title INSOMNIAPP
        #welcome-description A Cognitive-Behavioral Therapy Tool to Help You Sleep
        #app-info
          %p Cognitive-Behavioral Therapy is a technique that has been used to treat depression, anxiety and, lately, insomnia. CBT recognizes that our thoughts, emotions and behaviors interact in ways that can negatively or positively reinforce each other. InsomniApp was designed with those techniques in mind to help users sleep better at night.
          -# %p InsomniApp allows you to positively affect your thoughts and mood by writing in the app's diary and recording your to-do lists. It also allows you to set reminders for better behavior, such as when to have your last cup of coffee for day. Finally, it allows you to track your sleep and see your improvement.
    .login.small-12.medium-4.columns
      #partial
        #login-partial= render 'layouts/login'
        #signup-partial= render 'layouts/signup'

  - else
    .row
      .small-12.medium-3.large-3.columns
        = render 'layouts/sidebar'
      .small-12.medium-9.large-9.columns
        .flashes
          %p.notice= notice
          %p.alert= alert
        = yield